# ============================================================
# APPLICATION
# ============================================================
spring.application.name=payment-service
server.port=8082

# ============================================================
# DATABASE — base de datos PROPIA del payment-service
# La separación de BDs responde la pregunta de revisión:
# "¿particionaron también la base de datos?"
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/payments_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ============================================================
# RABBITMQ
# ============================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-attempts=3

# ============================================================
# PAGO SIMULADO
# Porcentaje de pagos que fallan (0.0 = nunca falla, 0.3 = 30% de fallo)
# Útil para demostrar la compensación Saga en demos
# ============================================================
app.payment.failure-rate=0.2

# ============================================================
# OPENTELEMETRY
# ============================================================
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=10s
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# ============================================================
# SWAGGER
# ============================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ============================================================
# LOGGING
# ============================================================
logging.level.com.ecommerce.payment=INFO
logging.level.org.springframework.amqp=INFO
